
#include "string.h"
#include "stdlib.h"
#include "stdarg.h"
#include "math.h"

//#include "stm32f10x_adc.h"
#include "stm32f10x_bkp.h"
//#include "stm32f10x_can.h"
//#include "stm32f10x_cec.h"
//#include "stm32f10x_crc.h"
//#include "stm32f10x_dac.h"
//#include "stm32f10x_dbgmcu.h"
#include "stm32f10x_dma.h"
#include "stm32f10x_exti.h"
#include "stm32f10x_flash.h"
//#include "stm32f10x_fsmc.h"
#include "stm32f10x_gpio.h"
//#include "stm32f10x_i2c.h"
#include "stm32f10x_iwdg.h"
#include "stm32f10x_pwr.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_rtc.h"
//#include "stm32f10x_sdio.h"
#include "stm32f10x_spi.h"
#include "stm32f10x_tim.h"
#include "stm32f10x_usart.h"
//#include "stm32f10x_wwdg.h"
#include "misc.h"

#include "gtw_type.h"
#include "hw_init.h"
#include "Protocol.h"
#include "gtw_UserApp.h"
#include "gtw_PoliceApp.h"
#include "gtw_ServerApp.h"
#include "gtw_SetupApp.h"
#include "gtw_EleDriver.h"
#include "gtw_DataCollector.h"
#include "gtw_LightApp.h"
#include "gtw_Illegal.h"
#include "queue.h"

#include "debug.h"
#include "flash_user.h"
#include "flash_driver.h"
#include "radio_user.h"
#include "radio_driver.h"
#include "calendar.h"
#include "utility.h"
#include "gps_driver.h"
#include "gprs_gsm_driver.h"
#include "wifibt_user.h"
#include "io_detection.h"
#include "wifibt_user.h"
#include "ElecDriverLic.h"
#include "gps_user.h"
#include "decoding_carno.h"
#include "smartcard_user.h"
#include "Stm32Flash.h"
#include "speech.h"
#include "mpu6050.h"
#include "inv_mpu.h"
#include "inv_mpu_dmp_motion_driver.h"



#ifdef __USE_USB__
#include "usb_main.h"
#endif

#ifdef __UCOS__
#include "os.h"
#endif
